### ISSUE TITLE
Stasis Prison still included

### ISSUE THREAD

**Issue by JackOverlord** [xanthics/poe_gen_gwennen#5]
![Screenshot_20211101-060914__01](https://user-images.githubusercontent.com/25202819/139624616-b115a312-b380-41a5-a2f5-931f6a236c9a.jpg)
![Screenshot_20211101-061109__01](https://user-images.githubusercontent.com/25202819/139624619-b1bf8d64-20bb-4ce8-acf5-7fdeb79d896c.jpg)
As you can see, despite Stasis Prison not being supposed to show up, it still does and gets included in the string.

**Comment by xanthics** [comment]
Fixed: a58b3c65f7a550ea0642e870fa5ee0e2d7c5dff6

Had updated another project and apparently thought I updated this one too.
